(() => {
"use strict";
const SK="smart_att_students_v3", AK="smart_att_records_v3";
let students=JSON.parse(localStorage.getItem(SK)||"[]");
let records=JSON.parse(localStorage.getItem(AK)||"[]");
let qrScanner=null,running=false,locked=false;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(SK,JSON.stringify(students));localStorage.setItem(AK,JSON.stringify(records))}
function makeId(){return window.crypto&&typeof crypto.randomUUID==="function"?crypto.randomUUID():"ID-"+Date.now()+"-"+Math.random().toString(36).slice(2)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
let toastTimer;
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),2500)}
window.go=function(p){if(running&&p!=="scanner")stopScan();document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="dashboard")dashboard();if(p==="students")renderStudents();if(p==="attendance")renderAttendance()};
document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>go(b.dataset.page)));
$("loginForm").addEventListener("submit",e=>{e.preventDefault();if($("loginUser").value.trim()==="admin"&&$("loginPass").value==="admin123"){$("loginScreen").hidden=true;$("app").hidden=false;dashboard();renderStudents();renderAttendance()}else toast("Invalid username or password")});
$("logout").addEventListener("click",()=>location.reload());
$("studentForm").addEventListener("submit",e=>{e.preventDefault();const edit=$("editId").value,n=$("name").value.trim(),r=$("roll").value.trim(),c=$("course").value.trim()||"Not specified";if(!n||!r)return toast("Name and roll number are required");if(students.some(s=>s.roll.toLowerCase()===r.toLowerCase()&&s.id!==edit))return toast("Roll number already exists");if(edit){const s=students.find(x=>x.id===edit);if(!s)return toast("Student not found");Object.assign(s,{name:n,roll:r,course:c});records.forEach(a=>{if(a.studentId===edit)Object.assign(a,{name:n,roll:r,course:c})});toast("Student updated")}else{students.push({id:makeId(),name:n,roll:r,course:c,createdAt:new Date().toISOString()});toast("Student added")}save();resetStudentForm();renderStudents();dashboard()});
$("cancelEdit").addEventListener("click",resetStudentForm);$("studentSearch").addEventListener("input",renderStudents);
function resetStudentForm(){$("studentForm").reset();$("editId").value="";$("formTitle").textContent="Add Student";$("cancelEdit").hidden=true}
function renderStudents(){const q=$("studentSearch").value.toLowerCase().trim(),a=students.filter(s=>`${s.name} ${s.roll} ${s.course}`.toLowerCase().includes(q));$("studentRows").innerHTML=a.length?a.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.roll)}</td><td>${esc(s.course)}</td><td><button class="smallbtn" onclick="showQR('${s.id}')">QR</button> <button class="smallbtn" onclick="editStudent('${s.id}')">Edit</button> <button class="smallbtn danger" onclick="delStudent('${s.id}')">Delete</button></td></tr>`).join(""):`<tr><td colspan="4" class="empty">No students found.</td></tr>`}
window.editStudent=function(id){const s=students.find(x=>x.id===id);if(!s)return;$("editId").value=s.id;$("name").value=s.name;$("roll").value=s.roll;$("course").value=s.course;$("formTitle").textContent="Edit Student";$("cancelEdit").hidden=false;window.scrollTo({top:0,behavior:"smooth"})};
window.delStudent=function(id){const s=students.find(x=>x.id===id);if(!s||!confirm(`Delete ${s.name} and all attendance records?`))return;students=students.filter(x=>x.id!==id);records=records.filter(x=>x.studentId!==id);save();renderStudents();dashboard();renderAttendance();$("qr").innerHTML="<p>Select QR from student list.</p>";$("downloadQR").hidden=true;toast("Student deleted")};
window.showQR=function(id){const s=students.find(x=>x.id===id);if(!s)return;if(typeof QRCode==="undefined")return toast("QR library is not loaded. Check internet connection.");const box=$("qr");box.innerHTML="";new QRCode(box,{text:JSON.stringify({app:"SMART_ATTENDANCE_V3",studentId:s.id}),width:210,height:210,correctLevel:QRCode.CorrectLevel.H});const p=document.createElement("p");p.innerHTML=`<b>${esc(s.name)}</b><br>Roll: ${esc(s.roll)}<br>${esc(s.course)}`;box.appendChild(p);$("downloadQR").hidden=false;$("downloadQR").onclick=()=>{const c=box.querySelector("canvas"),i=box.querySelector("img"),href=c?c.toDataURL("image/png"):i?i.src:"";if(!href)return toast("QR image is not ready");const a=document.createElement("a");a.href=href;a.download=`${s.roll}-attendance-QR.png`;a.click()}};
function cameraStatus(m,t=""){$("camMsg").textContent=m;$("camMsg").className=t}
$("start").addEventListener("click",startScan);$("stop").addEventListener("click",stopScan);$("retry").addEventListener("click",()=>{ $("scanResult").textContent="Waiting for scan…";$("scanResult").className="result";startScan()});
async function startScan(){if(!students.length){toast("Register a student first");go("students");return}if(typeof Html5Qrcode==="undefined"){cameraStatus("QR scanner library failed to load. Check your internet connection.","err");return}if(running)return;locked=false;$("start").hidden=true;$("stop").hidden=false;$("retry").hidden=true;cameraStatus("Requesting camera permission…");try{if(qrScanner)try{await qrScanner.clear()}catch(_){}qrScanner=new Html5Qrcode("reader");const cfg={fps:10,qrbox:{width:250,height:250},aspectRatio:1};try{await qrScanner.start({facingMode:{exact:"environment"}},cfg,scanOK,()=>{})}catch(_){try{await qrScanner.clear()}catch(__){}qrScanner=new Html5Qrcode("reader");await qrScanner.start({facingMode:"environment"},cfg,scanOK,()=>{})}running=true;cameraStatus("Camera active — point it at the student QR.","ok")}catch(err){console.error("Camera error:",err);running=false;$("start").hidden=false;$("stop").hidden=true;$("retry").hidden=false;cameraStatus("Camera failed. Use HTTPS/localhost and allow camera permission.","err")}}
async function stopScan(){if(qrScanner){try{if(running)await qrScanner.stop()}catch(_){}try{await qrScanner.clear()}catch(_){}}qrScanner=null;running=false;locked=false;$("start").hidden=false;$("stop").hidden=true;$("retry").hidden=true;$("reader").innerHTML="";cameraStatus("Scanner stopped.")}
async function scanOK(text){if(locked)return;locked=true;try{const d=JSON.parse(text);if(!d||!d.studentId||!String(d.app).startsWith("SMART_ATTENDANCE"))throw new Error("Invalid QR");const s=students.find(x=>x.id===d.studentId);if(!s){$("scanResult").textContent="❌ This QR is not registered in this system.";$("scanResult").className="result error";toast("Unknown QR code");locked=false;return}const now=new Date(),date=localDate(now),time=now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});if(records.some(a=>a.studentId===s.id&&a.date===date&&a.status==="Present")){$("scanResult").textContent=`⚠️ ${s.name} is already marked Present today.`;$("scanResult").className="result warning";toast("Already marked today");await stopScan();return}records.push({id:makeId(),studentId:s.id,name:s.name,roll:s.roll,course:s.course,date,time,status:"Present",stamp:now.toISOString()});save();$("scanResult").textContent=`✅ ${s.name} marked Present at ${time}`;$("scanResult").className="result success";toast("Attendance marked");dashboard();renderAttendance();await stopScan()}catch(err){console.error("QR error:",err);$("scanResult").textContent="❌ Invalid QR code.";$("scanResult").className="result error";locked=false}}
function dashboard(){const d=localDate(),today=records.filter(x=>x.date===d),present=new Set(today.filter(x=>x.status==="Present").map(x=>x.studentId)).size;$("sStudents").textContent=students.length;$("sPresent").textContent=present;$("sAbsent").textContent=Math.max(0,students.length-present);$("sRate").textContent=(students.length?Math.round(present/students.length*100):0)+"%";const r=[...records].sort((a,b)=>String(b.stamp).localeCompare(String(a.stamp))).slice(0,6);$("recent").innerHTML=r.length?r.map(x=>`<p>✅ <b>${esc(x.name)}</b> — ${esc(x.date)} ${esc(x.time)}</p>`).join(""):"<p>No attendance yet.</p>"}
window.markAllAbsent=function(){if(!students.length)return toast("No students registered");const d=localDate(),p=new Set(records.filter(x=>x.date===d&&x.status==="Present").map(x=>x.studentId)),a=students.filter(s=>!p.has(s.id));if(!a.length)return toast("All students already marked Present");if(!confirm(`Mark ${a.length} remaining student(s) Absent today?`))return;const now=new Date();a.forEach(s=>records.push({id:makeId(),studentId:s.id,name:s.name,roll:s.roll,course:s.course,date:d,time:now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"}),status:"Absent",stamp:now.toISOString()}));save();dashboard();renderAttendance();toast("Remaining students marked Absent")};
$("filterDate").addEventListener("change",renderAttendance);$("filterText").addEventListener("input",renderAttendance);
function renderAttendance(){const d=$("filterDate").value,q=$("filterText").value.toLowerCase().trim(),a=records.filter(x=>(!d||x.date===d)&&(!q||`${x.name} ${x.roll} ${x.course} ${x.status}`.toLowerCase().includes(q))).sort((a,b)=>String(b.stamp).localeCompare(String(a.stamp)));$("attRows").innerHTML=a.length?a.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.time)}</td><td>${esc(x.name)}</td><td>${esc(x.roll)}</td><td>${esc(x.course)}</td><td class="${x.status==="Present"?"present":"absent"}">${esc(x.status)}</td></tr>`).join(""):`<tr><td colspan="6" class="empty">No records found.</td></tr>`}
window.clearFilter=function(){$("filterDate").value="";$("filterText").value="";renderAttendance()};
window.exportCSV=function(){if(!records.length)return toast("No records to export");const rows=[["Date","Time","Name","Roll","Course","Status"],...records.map(x=>[x.date,x.time,x.name,x.roll,x.course,x.status])],csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="attendance-report.csv";a.click();URL.revokeObjectURL(url);toast("CSV exported")};
dashboard();renderStudents();renderAttendance();
})();